version: '3.9'
services:
  auto-tool-db:
    image: postgres
    container_name: auto-tool-investigation-db
    ports:
      - "5433:5432"
    command: postgres -c 'max_connections=1000'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auto_tool_investigation_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - auto-tool-investigation-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql  # table and trigger initiation

volumes:
  auto-tool-investigation-db:
